file_manager/files/urls.py
from django.urls import path

from . import views

app_name = 'files'

urlpatterns = [
    path('', views.ListFilesView.as_view(), name='list'),
    path('upload/', views.UploadFileView.as_view(), name='upload'),
    path('download/<int:file_id>/', views.DownloadFileView.as_view(),
         name='download'),
    # We'd probably want to split API URLs into their own included URLconf
    # here if we had more than just the one:
    path('api/search/', views.FileSearchAPIView.as_view(), name='api_search')
]

file_manager/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

from file_manager import user_management_views


urlpatterns = [
    path('', RedirectView.as_view(pattern_name='files:list')),
    path('admin/', admin.site.urls),
    path('files/', include('file_manager.files.urls')),
    path('login/', LoginView.as_view(
        template_name='user_management/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', user_management_views.UserRegistrationView.as_view(),
         name='user_registration')
]

file_manager/files/models.py
from django.contrib.auth.models import User
import django.db.models as django_models


def _get_user_file_path(instance, filename):
    return f'user_{instance.owner_id}/{filename}'


class FileUploadManager(django_models.Manager):

    """Default object manager for the FileUpload model."""

    def visible_to_user(self, user):
        """Retrieve all the files a user can see, public or private."""
        queryset = self.get_queryset()
        return queryset\
            .filter(django_models.Q(owner=user) |
                    django_models.Q(is_public=True))\
            .order_by('-created_at')


class FileUpload(django_models.Model):

    """Represents uploaded files."""

    objects = FileUploadManager()

    upload = django_models.FileField(
        upload_to=_get_user_file_path, verbose_name='File to upload',
        help_text='Select the file to upload')
    name = django_models.CharField(
        max_length=255, help_text='The original name of the file')
    owner = django_models.ForeignKey(User, on_delete=django_models.CASCADE)
    is_public = django_models.BooleanField(
        default=False, verbose_name='Make file public?',
        help_text='Public files are available to all users.')

    created_at = django_models.DateTimeField(auto_now_add=True)
    updated_at = django_models.DateTimeField(auto_now=True)

file_manager/files/forms.py
from django.forms import ModelForm

from . import models


class FileUploadForm(ModelForm):
    class Meta:
        model = models.FileUpload
        fields = ['upload', 'is_public']

file_manager/files/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import FileResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.views import View
from django.urls import reverse

from . import forms
from . import models


class UploadFileView(LoginRequiredMixin, View):

    """View which allows users to upload new files."""

    def get(self, request, *args, **kwargs):
        form = forms.FileUploadForm()
        return TemplateResponse(request, 'files/upload_file.html',
                                context={'form': form})

    def post(self, request, *args, **kwargs):
        form = forms.FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            file_upload = form.save(commit=False)
            file_upload.owner = request.user
            file_upload.name = request.FILES['upload'].name
            file_upload.save()
            return redirect('files:list')
        else:
            return TemplateResponse(request, 'files/upload_file.html',
                                    context={'form': form})


class ListFilesView(LoginRequiredMixin, View):

    """
    View which allows users to see a list of their files, plus any that are
    publically-available.
    """

    def get(self, request, *args, **kwargs):
        files = models.FileUpload.objects.visible_to_user(request.user)
        return TemplateResponse(request, 'files/list_files.html',
                                context={'files': files})


class DownloadFileView(LoginRequiredMixin, View):

    """View which allows users to download files that are visible to them."""

    def get(self, request, *args, **kwargs):
        file_id = kwargs.get('file_id')
        visible_files = models.FileUpload.objects.visible_to_user(request.user)
        file_upload = get_object_or_404(visible_files, id=file_id)

        return FileResponse(file_upload.upload, as_attachment=True,
                            filename=file_upload.name)


class FileSearchAPIView(LoginRequiredMixin, View):

    """
    An API view which allows users to search for a files whose names contain
    the given search string. Multiple strings can be provided by specifying the
    query parameter multiple times, e.g. 'q=foo&q=bar', in which case the
    only files matching all the strings will be returned.
    """

    def get(self, request, *args, **kwargs):
        search_strings = request.GET.getlist('q')

        matched_files = models.FileUpload.objects.visible_to_user(request.user)

        for s in search_strings:
            matched_files = matched_files.filter(name__icontains=s)

        result_data = [self._render_file_upload(f) for f in matched_files]

        # We have to set safe=False to allow us to render an array, but we
        # should decide how concerned we are about array constructor poisoning
        # if our clients are likely to be using ECMAScript < 5
        return JsonResponse(result_data, safe=False)

    def _render_file_upload(self, file_upload):
        return {
            'name': file_upload.name,
            'created_at': file_upload.created_at.isoformat(),
            'is_public': file_upload.is_public,
            'download_url': reverse('files:download',
                                    kwargs={'file_id': file_upload.id})}

file_manager/files/templates/files/list_files.html
{% extends 'base.html' %}

{% block title %}Available Files{% endblock %}

{% block content %}
    <h1>Available Files</h1>
    <p><a href="{% url 'files:upload' %}">Upload New File</a> &bull; <a href="{% url 'logout' %}">Log Out</a></p>
    <ul>
        {% for file in files %}
        <li>
            <strong><a href="{% url 'files:download' file_id=file.id %}">{{ file.name }}</a></strong> {{ file.created_at | date }} {{ file.created_at | time }} {% if file.is_public %}[<em>public</em>]{% endif %}
        </li>
        {% empty %}
        <li>You have no files</li>
        {% endfor %}
    </ul>
{% endblock %}

file_manager/files/templates/files/upload_file.html
{% extends 'base.html' %}

{% block title %}Upload a file{% endblock %}

{% block content %}
    <h1>Upload New File</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload File</button>
    </form>
{% endblock %}

file_manager/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}File Manager{% endblock %}</title>
</head>
<body>
    {% block content %}
        <p>Content goes here.</p>
    {% endblock %}
</body>
</html>

file_manager/templates/user_management/login.html
{% extends 'base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
    <h1>Log in to continue</h1>
    <p>Need to <a href="{% url 'user_registration' %}">register for an account</a>?</p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="next" value="{{ next }}">
        <button type="submit">Log In</button>
    </form>
{% endblock %}

file_manager/templates/user_management/user_registration.html
{% extends 'base.html' %}

{% block title %}Create an account{% endblock %}

{% block content %}
    <h1>Create an Account</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Account</button>
    </form>
{% endblock %}